
RATE_CONFIG = dict()

RATE_CONFIG["STREET_INFRASTRUCTURE"] = dict()

RATE_CONFIG["STREET_INFRASTRUCTURE"]["COMPACT_TRANSFORMER"] = {
    "RATE": 65000.00
}

RATE_CONFIG["SIGNAGE"] = dict()

RATE_CONFIG["SIGNAGE"]["PARKING_SIGNAGE"] = {
    "RATE": 3309.32,
    "NORM_CONSTANTS": {
         "INTERVAL": 50.0, 
         "ROAD_SEGMENT_PERCENTAGE": 0.3 
    }, 
}


RATE_CONFIG["PARKING"] = dict()

RATE_CONFIG["PARKING"]["PARKING_METERS"] = {
    "SQL_CONFIG": "ROAD_ID_PARKING_METERS",
    "RATE": 20000.00,
    "NORM_CONSTANTS": {
         "INTERVAL": 150.0, 
         "ROAD_SEGMENT_PERCENTAGE": 0.3 
    }, 
}
