
RATE_CONFIG = dict()

RATE_CONFIG["STREET_INFRASTRUCTURE"] = dict()

RATE_CONFIG["STREET_INFRASTRUCTURE"]["COMPACT_TRANSFORMER"] = {
    "SQL_CONFIG": "ROAD_ID_TRANSFORMER_ISSUE_COUNT",
    "RATE": 65000.00
}

RATE_CONFIG["SIGNAGE"] = dict()

RATE_CONFIG["SIGNAGE"]["PARKING_SIGNAGE"] = {
    "SQL_CONFIG": "ROAD_ID_NO_PARKING_SIGNAGE_COUNT",
    "RATE": 3309.32
}


RATE_CONFIG["PARKING"] = dict()

RATE_CONFIG["PARKING"]["PARKING_METERS"] = {
    "SQL_CONFIG": "ROAD_ID_PARKING_METERS",
    "RATE": 20000.00
}

RATE_CONFIG["PARKING"]["PARKING_MARKING_2W"] = {
    "SQL_CONFIG": "ROAD_ID_PARKING_MARKING_2W",
    "RATE": 454.74
}

RATE_CONFIG["PARKING"]["PARKING_MARKING_4W"] = {
    "SQL_CONFIG": "ROAD_ID_PARKING_MARKING_4W",
    "RATE": 454.74
}

RATE_CONFIG["PARKING"]["NO_PARKING_SIGNAGE"] = {
    "SQL_CONFIG": "ROAD_ID_NO_PARKING_SIGNAGE_COUNT",
    "RATE": 3309.32
}